### ISSUE TITLE
Not working since today

### ISSUE THREAD

**Issue by manuelkamp** [rootje/hoymiles-mqtt#3]
Maybe hoymiles changed api urls? I get 404 if i open the urls in browser...

```
root@srv-automation:~# /usr/bin/python3 /opt/hoymiles/solar.py
Starting program
Checking every 450 seconds for new data from Hoymiles
Checking now...
Traceback (most recent call last):
  File "/opt/hoymiles/solar.py", line 97, in <module>
    hoymiles = Energy(USERNAME,USERPASSWORD)
  File "/opt/hoymiles/solar.py", line 40, in __init__
    self.cookie = self.authentication_cookie()
  File "/opt/hoymiles/solar.py", line 44, in authentication_cookie
    response_auth = json.loads(requests.post("https://global.hoymiles.com/platform/api/gateway/iam/auth_login", data={'user_name': self.username, 'password': self.password}).text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by rootje** [comment]
I've noticed also. The url's changed and it seems the login procedure as well. Need to find time to figure this one out. Could take a while...

**Comment by manuelkamp** [comment]
thanks for the quick confirmation - at least I am now sure, it is not a problem on my side :)
If you need some more testing (i have it running on bare metal - not docker), or something else, just ping me.

**Comment by rootje** [comment]
So I think I've fixed the issue. Compiled a new container on the docker-hub as well. On my end it seems to be working again. Hoymiles changed the authorization of the API and the url's. Server.py is updated on a few places.

Please confirm if it works on your end!

**Comment by manuelkamp** [comment]
Thank you, i applied the changes to my script (since I have replaced mqtt with writing into mysql db) and i get solar data now again.

I saw you removed the method "authentication_cookie", but in the errorhandling it would still get called. however, it does at least pull data in a happy path now :)

**Comment by rootje** [comment]
I'm glad it works for you.thank you for replying and testing.
